from turtle import *

def dibujar_piedra():
    pantalla = Screen()
    pantalla.setup(width=300, height=300)
    pantalla.title("Piedra")
    pantalla.bgcolor("white")
    texto = Turtle()
    texto.penup()
    texto.hideturtle()
    texto.goto(-100, 120)
    texto.write("El usuario elige piedra", font=("Arial", 14, "bold"))
    piedra = Turtle()
    piedra.color("green")
    piedra.pensize(5)
    piedra.penup()
    piedra.goto(-50, 75)
    piedra.pendown()
    piedra.goto(50, 75)
    piedra.goto(75, 50)
    piedra.goto(75, -50)
    piedra.goto(50, -75)
    piedra.goto(-50, -75)
    piedra.goto(-75, -50)
    piedra.goto(-75, 50)
    piedra.goto(-50, 75)
    piedra.penup()
    piedra.goto(-50, 75)
    piedra.pendown()
    piedra.goto(-50, -75)
    piedra.penup()
    piedra.goto(40, 60)
    piedra.pendown()
    piedra.goto(-40, 60) 
    piedra.penup()
    piedra.goto(60, 60)  # Movemos el punto inicial hacia abajo (y = 40)
    piedra.pendown()
    piedra.goto(-60, 60) 
    piedra.penup()
    piedra.goto(50, 75)
    piedra.pendown()
    piedra.goto(50, -75)
    piedra.hideturtle()
    pantalla.mainloop()

dibujar_piedra()
